// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAmtaZIZ-fb_ookbzV_jSvZIVE7hEXnFM',
    appId: '1:246261392299:web:db008233de3648b79328ee',
    messagingSenderId: '246261392299',
    projectId: 'trabalho-flutter-3f3c7',
    authDomain: 'trabalho-flutter-3f3c7.firebaseapp.com',
    storageBucket: 'trabalho-flutter-3f3c7.firebasestorage.app',
    measurementId: 'G-NB12GR1TTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRBxgrq26McA3drrRz6MkxYHDoaLi4WOA',
    appId: '1:246261392299:android:7a405e999a77d7f89328ee',
    messagingSenderId: '246261392299',
    projectId: 'trabalho-flutter-3f3c7',
    storageBucket: 'trabalho-flutter-3f3c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAotJIENutGzIjLS7SR0lnnKDVNB6obZS8',
    appId: '1:246261392299:ios:4d5f1435887a98759328ee',
    messagingSenderId: '246261392299',
    projectId: 'trabalho-flutter-3f3c7',
    storageBucket: 'trabalho-flutter-3f3c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAotJIENutGzIjLS7SR0lnnKDVNB6obZS8',
    appId: '1:246261392299:ios:4d5f1435887a98759328ee',
    messagingSenderId: '246261392299',
    projectId: 'trabalho-flutter-3f3c7',
    storageBucket: 'trabalho-flutter-3f3c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAmtaZIZ-fb_ookbzV_jSvZIVE7hEXnFM',
    appId: '1:246261392299:web:bccc30535a9aa2b59328ee',
    messagingSenderId: '246261392299',
    projectId: 'trabalho-flutter-3f3c7',
    authDomain: 'trabalho-flutter-3f3c7.firebaseapp.com',
    storageBucket: 'trabalho-flutter-3f3c7.firebasestorage.app',
    measurementId: 'G-76BC9XNG3D',
  );
}
